[project]
name = "veryflashy"
version = "0.1"
authors = [ { name="Dan Lenski", email="dlenski@gmail.com" } ]
description = "USB flash drive inspection tool"
readme = "README.md"
keywords = [ "USB", "NAND", "utility" ]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: System :: Hardware",
]
dependencies = [
    "py-sg>=0.17",
    "humanize",
    "hexdump",
    "requests",
]

[project.license]
"text" = "GPL-3.0-or-later AND GPL-3.0-only"

[project.urls]
"Homepage" = "https://github.com/dlenski/veryflashy"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 40.9.0"]

[project.scripts]
veryflashy = "veryflashy.__main__:main"

[tool.setuptools.package-data]
veryflashy = ["data/*.json", "data/*.txt"]
